# Generated by Django 3.0.5 on 2020-05-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='added_at',
            new_name='date',
        ),
    ]
